sudo: required
dist: trusty

script: curl -s https://raw.githubusercontent.com/Shopify/themekit/master/scripts/install | sudo python
deploy:
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
